### ISSUE TITLE
Support .* for routes

### ISSUE THREAD

**Issue by raadad** [pillarjs/routington#24]
Currently /path/:restofroute(.*) - does not match /path/abc/def/ghi/jkl/mnop
Is this not supported, or is there an alternate way of doing this?

**Comment by daliwali** [comment]
:+1: to this, just tried it and it doesn't seem work.

**Comment by raadad** [comment]
path-to-regexp seems to support this /:foo*
however this comes up as an error with the trie router.

**Comment by daliwali** [comment]
My workaround for this is extremely ugly:

```js
[
  '/(.*)',
  '/(.*)/(.*)',
  '/(.*)/(.*)/(.*)',
  '/(.*)/(.*)/(.*)/(.*)',
  '/(.*)/(.*)/(.*)/(.*)/(.*)'
]
```

@jonathanong pls :(

**Comment by jonathanong** [comment]
globs are an antipattern. :) this was intentional. i do actually use both routington and path-to-regexp depending on what i need though

**Comment by jonathanong** [comment]
http://www.jongleberry.com/wildcard-routing-is-an-anti-pattern.html blog post for you :)

**Comment by yoshuawuyts** [comment]
@jonathanong neat writeup, thanks for sharing your thoughts ^^

**Comment by daliwali** [comment]
The use case I have is serving a proxy endpoint, so that any request to `/proxy/:endpoint*` would be matched, and also serving an `index.html` for arbitrary routes generated from a web browser using History API, which is opaque to the server. Thanks for the blog post though.
